# Generated by Django 3.2.9 on 2022-02-28 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransientEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('beam', models.IntegerField(verbose_name='Trigger Beam')),
                ('dm', models.FloatField(verbose_name='DM')),
                ('sn', models.FloatField(verbose_name='SNR')),
                ('boxcar', models.IntegerField(verbose_name='Boxcar')),
                ('width_value', models.FloatField(verbose_name='Pulse Width (ms)')),
                ('mjd', models.FloatField(verbose_name='MJD')),
                ('latency_ms', models.FloatField(verbose_name='Latency(ms)')),
                ('ra', models.FloatField(blank=True, verbose_name='Right Asension')),
                ('dec', models.FloatField(blank=True, verbose_name='Declination')),
            ],
        ),
        migrations.CreateModel(
            name='Veto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.CharField(choices=[(0, 'Unverified'), (1, 'FRB'), (2, 'Pulsar'), (-1, 'RFI'), (3, 'Unknown')], default=0, max_length=20)),
                ('reason', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('username', models.CharField(default='Anonymous', max_length=20)),
                ('frb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.transiententry')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('choice_text', models.CharField(max_length=200)),
                ('frb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.transiententry')),
            ],
        ),
        migrations.CreateModel(
            name='Multimessenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Info')),
                ('username', models.CharField(default='Anonymous', max_length=20)),
                ('ra', models.FloatField(blank=True, verbose_name='Right Asension')),
                ('dec', models.FloatField(blank=True, verbose_name='Declination')),
                ('ra_err', models.FloatField(blank=True, verbose_name='RA err')),
                ('dec_err', models.FloatField(blank=True, verbose_name='Dec err')),
                ('upload', models.FileField(blank=True, upload_to='uploads/', verbose_name='Uploaded File')),
                ('frb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.transiententry')),
            ],
        ),
    ]
