# Generated by Django 3.2.9 on 2022-02-10 03:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransientEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('beam', models.IntegerField(verbose_name='Trigger Beam')),
                ('dm', models.FloatField(verbose_name='DM')),
                ('sn', models.FloatField(verbose_name='SNR')),
                ('boxcar', models.IntegerField(verbose_name='Boxcar')),
                ('width_value', models.FloatField(verbose_name='Pulse Width (ms)')),
                ('mjd', models.FloatField(verbose_name='MJD')),
                ('latency_ms', models.FloatField(verbose_name='Latency(ms)')),
            ],
        ),
        migrations.CreateModel(
            name='Veto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify', models.CharField(default='Unverified', max_length=20)),
                ('reason', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('username', models.CharField(default='Anonymous', max_length=20)),
                ('frb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.transiententry')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('choice_text', models.CharField(max_length=200)),
                ('frb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.transiententry')),
            ],
        ),
        migrations.CreateModel(
            name='Multimessenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('RA', models.FloatField(verbose_name='R.A.')),
                ('Dec', models.FloatField(verbose_name='Declination')),
                ('ra_err', models.FloatField(verbose_name='ra err')),
                ('dec_err', models.FloatField(verbose_name='dec err')),
                ('frb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.transiententry')),
            ],
        ),
    ]
