# Generated by Django 3.2.9 on 2022-02-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_multimessenger_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimessenger',
            name='username',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
