# Generated by Django 3.2.9 on 2022-02-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_multimessenger_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimessenger',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='multimessenger',
            name='Dec',
            field=models.FloatField(blank=True, verbose_name='Declination'),
        ),
        migrations.AlterField(
            model_name='multimessenger',
            name='RA',
            field=models.FloatField(blank=True, verbose_name='Right Asension'),
        ),
        migrations.AlterField(
            model_name='multimessenger',
            name='dec_err',
            field=models.FloatField(blank=True, verbose_name='Dec err'),
        ),
        migrations.AlterField(
            model_name='multimessenger',
            name='ra_err',
            field=models.FloatField(blank=True, verbose_name='RA err'),
        ),
        migrations.AlterField(
            model_name='veto',
            name='verify',
            field=models.CharField(choices=[(0, 'Unverified'), (1, 'FRB'), (2, 'Pulsar'), (-1, 'RFI'), (3, 'Unknown')], default=0, max_length=20),
        ),
    ]
